"""empty message

Revision ID: c69340c2eb81
Revises: dff062585bbc
Create Date: 2019-09-28 14:59:35.606751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69340c2eb81'
down_revision = 'dff062585bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('InTicket')
    op.drop_table('Item')
    op.drop_table('OutTicker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OutTicker',
    sa.Column('identifier', sa.VARCHAR(length=6), nullable=False),
    sa.Column('items', sa.VARCHAR(), nullable=True),
    sa.Column('giver', sa.VARCHAR(), nullable=True),
    sa.Column('receiver', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('identifier'),
    sa.UniqueConstraint('items')
    )
    op.create_table('Item',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('InTicket',
    sa.Column('identifier', sa.VARCHAR(length=6), nullable=False),
    sa.Column('items', sa.VARCHAR(), nullable=True),
    sa.Column('giver', sa.VARCHAR(), nullable=True),
    sa.Column('receiver', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('identifier'),
    sa.UniqueConstraint('items')
    )
    op.create_table('Users',
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.INTEGER(), nullable=True),
    sa.Column('tickets', sa.VARCHAR(), nullable=True),
    sa.Column('items_requested', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
